#float32 heading
#float32 latitude
#float32 longitude
#float32 altitude

#int16 airspeed_raw
#int16 accx_raw
#int16 accy_raw
#int16 accz_raw
#int16 gyrox_raw
#int16 gyroy_raw
#int16 gyroz_raw
#int16 dummy1
#int16 dummy2

uint64 timestamp		# time since system start (microseconds)
float32 latitude
float32 longitude
float32 altitude

int16 roll_angle
int16 pitch_angle
int16 yaw_angle
int16 roll_rate
int16 pitch_rate
int16 yaw_rate
int16 x_n
int16 y_e
int16 z_d
int16 v_n
int16 v_e
int16 v_d