#!/bin/sh
#
# @name F450 Quadrotor x (HILS)
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 feed-through of RC AUX1 channel
# @output MAIN6 feed-through of RC AUX2 channel
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
# @output AUX4 feed-through of RC FLAPS channel
#
# @maintainer Dongwon Jung <djung@kau.ac.kr>
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x

set PWM_OUT 1234

if [ $AUTOCNF = yes ]
then
	param set MC_ROLL_P 0.65
	param set MC_ROLLRATE_P 0.015
	param set MC_ROLLRATE_I 0.0
	param set MC_ROLLRATE_D 0.0
	param set MC_PITCH_P 0.65
	param set MC_PITCHRATE_P 0.015
	param set MC_PITCHRATE_I 0.0
	param set MC_PITCHRATE_D 0.0
	param set MC_YAW_P 0.28
	param set MC_YAWRATE_P 0.02
	param set MC_YAWRATE_I 0.0
	param set MC_YAWRATE_D 0.0
	param set MPC_XY_CRUISE 10.0
	param set MPC_XY_P 0.02
	param set MPC_XY_VEL_D 0.005
	param set MPC_XY_VEL_I 0.0
	param set MPC_XY_VEL_MAX 6.0
	param set MPC_XY_VEL_P 0.06
	param set MPC_Z_P 0.2
	param set MPC_Z_TRAJ_P 0.1
	param set MPC_Z_VEL_D 0.0
	param set MPC_Z_VEL_I 0.01
	param set MPC_Z_VEL_MAX_DN 1.0
	param set MPC_Z_VEL_MAX_UP 1.0
	param set MPC_Z_VEL_P 0.1

fi
