#!/bin/sh
#
# @name DevCopter Quadrotor x (HILS)
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

	param set MC_ROLL_P 0.66
	param set MC_ROLLRATE_P 0.016
	param set MC_ROLLRATE_I 0.0
	param set MC_ROLLRATE_D 0.0
	param set MC_PITCH_P 0.66
	param set MC_PITCHRATE_P 0.016
	param set MC_PITCHRATE_I 0.0
	param set MC_PITCHRATE_D 0.0
	param set MC_YAW_P 0.29
	param set MC_YAWRATE_P 0.03
	param set MC_YAWRATE_I 0.0
	param set MC_YAWRATE_D 0.0
	param set MPC_XY_CRUISE 10.1
	param set MPC_XY_P 0.02
	param set MPC_XY_VEL_D 0.006
	param set MPC_XY_VEL_I 0.0
	param set MPC_XY_VEL_MAX 4.0
	param set MPC_XY_VEL_P 0.07
	param set MPC_Z_P 0.3
	param set MPC_Z_TRAJ_P 0.2
	param set MPC_Z_VEL_D 0.0
	param set MPC_Z_VEL_I 0.02
	param set MPC_Z_VEL_MAX_DN 1.0
	param set MPC_Z_VEL_MAX_UP 1.0
	param set MPC_Z_VEL_P 0.2

