
enum SERIAL_COM_PARSE_STATE {
	SERIAL_COM_PARSE_STATE0_UNSYNC = 0,
	SERIAL_COM_PARSE_STATE1_SYNC,
	SERIAL_COM_PARSE_STATE2_GOT_DIGIT0,
	SERIAL_COM_PARSE_STATE3_GOT_DOT,
	SERIAL_COM_PARSE_STATE4_GOT_DIGIT1,
	SERIAL_COM_PARSE_STATE5_GOT_DIGIT2,
	SERIAL_COM_PARSE_STATE6_GOT_CARRIAGE_RETURN
};

int serial_com_parser(char c, char *parserbuf, unsigned *parserbuf_index, enum SERIAL_COM_PARSE_STATE *state, float *dist);
